name: Build cambia
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  npm:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm ci
        working-directory: web
      - name: Generate the static site
        run: npm run build
        working-directory: web
      - name: Upload static site files
        uses: actions/upload-artifact@v4
        with:
          name: webui
          path: web/build

  cargo:
    name: Build binaries
    needs: npm
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: cambia-linux-amd64
          - os: ubuntu-24.04-arm
            artifact_name: cambia-linux-arm64
          - os: windows-latest
            artifact_name: cambia-windows-amd64
          - os: macos-latest
            artifact_name: cambia-macos-arm64
            binary_name: cambia
          - os: macos-15-intel
            artifact_name: cambia-macos-amd64
    steps:
      - uses: actions/checkout@v4
      - name: Download static site files
        uses: actions/download-artifact@v4
        with:
          name: webui
          path: web/build
      - uses: dtolnay/rust-toolchain@stable
      - name: Build w/ experimental rippers
        run: cargo build --release --features experimental_rippers
      - name: Rename binaries
        shell: bash
        run: mv target/release/cambia${{ matrix.os == 'windows-latest' && '.exe' || '' }} target/release/${{ matrix.artifact_name }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/release/${{ matrix.artifact_name }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Create release
    needs: cargo
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: cambia-*
          merge-multiple: true
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Cambia ${{ github.ref_name }}
          files: dist/*
