name: Build cambia
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  npm:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install
        working-directory: web
      - name: Generate the static site
        run: npm run build
        working-directory: web
      - name: Upload static site files
        uses: actions/upload-artifact@v4
        with:
          name: webui
          path: web/build

  cargo:
    name: Build binaries
    needs: npm
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Download static site files
        uses: actions/download-artifact@v4
        with:
          name: webui
          path: web/build
      - uses: dtolnay/rust-toolchain@stable
      - name: Build w/ experimental rippers
        run: cargo build --release --features experimental_rippers
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: cambia-${{ matrix.os }}
          path: target/release/cambia${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    name: Create GitHub Release
    needs: cargo
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: cambia-ubuntu-latest
          path: dist/linux
      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: cambia-windows-latest
          path: dist/windows
      - name: Download macOS binary
        uses: actions/download-artifact@v4
        with:
          name: cambia-macos-latest
          path: dist/macos
      - name: Rename binaries
        run: |
          mv dist/linux/cambia dist/cambia-linux
          mv dist/windows/cambia.exe dist/cambia-windows.exe
          mv dist/macos/cambia dist/cambia-macos
      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Cambia ${{ github.ref_name }}
          files: dist/*
